### ISSUE TITLE
Works with Arduino IDE 1.6.8 and ESP8266 released ver 2.1

### ISSUE THREAD

**Issue by Defragster** [nailbuster/myWebServer#2]
Just tested this to work on the indicated IDE 1.6.8 with Board Mgr updated to 2.1!

I had an issue with TIME library during IDE compile - I worked with maintainer Paul@PJRC and there is a fix for that on GitHub.

I'm liking what you've done here.

Not sure how to ask a series of questions - so I'll attempt the obvious:

I want to add MQTT into this sample on the Arduino myWebServer - not NodeMCU  with the food cooker. Is there a simple path for that?  I'm looking to have multiple ESP's find each other through a local server (windows). I see the /cloudgen.html 'MQTT Configure' - is that a supported first step?

Is there a way to use the OTA identification the way the Arduino IDE does to PING other online ESP units to find their IP's? Or is there another scheme for this I should know about?

I see the GZip encoded files - it seems that relies on the calling browser to decode and the decoder is not part of myWebServer?  How did you get the .GZ compressed bytes to include in the htmlEmbed.h file?

**Comment by nailbuster** [comment]
good to know its working with 1.6.8 and 2.1!

you can grab the mqttlink files (.h, .cpp) from the other project and use them in your own project.  You'll need to remove/add some code so that it will work for your needs but its there so that you can see how I got mqtt working.  And yes, you can use the cloudgen.html file as a starting point for your setup html.

there are some examples on esp8266.com forums in discovery of other units....its probably just using UDP to send/receive special messages....

to use gzip files,   just take your html file (myfile.html)  and use something like 7.zip program to creat a gzip version of the file and name it like myfile.html.gz,  put that file into the spiffs folder and just link to it by /myfile.html   (no gz extension) if a gz version is found then it will be used automatically.  You don't need to embed into an .h file, just put the file into spiffs.  if you want to embed then theres some free utilities that convert bin files to c++ array like I used....

let me know how it goes....

**Comment by Defragster** [comment]
Indeed - nice to see the ESP support improving and being stable!

I'll get those mqqt files and have a go - I haven't tried the nodemcu so I wasn't sure how useful/similar the code would be to study - and I definitely won't be using the steak cooker hardware ;) 

I've seen UDP noted as a good place to start, but I haven't tried that yet - wasn't sure if the IDE broadcast/detection of the OTA would be a good start or not since it is already there.  I assumed the actual OTA portion could be neutered so it was just there for unit ID.  MQTT - as long as you have a server could provide a transfer scheme, though UDP broadcast might be the best answer.

Thanks for the gz details - the compression at 2 or 4 to 1 looks handy.  I looked for the bin to array type utility and came up empty.

**Comment by nailbuster** [comment]
bin to array type I used was here:  https://sourceforge.net/projects/bin2header/

**Comment by Defragster** [comment]
To add gzip to the image, cool - thanks for the link -

**Comment by Defragster** [comment]
nailbuster - Hello!  

I got pulled away from this for stuff - including getting on the Teensy 3.6 beta that just shipped their Kickstarter!

Have you been keeping up with this on ESP 8266 at all?  My IDE is now at 1.6.12 and I see my Arduino 2.1 is OLD and the new version is at 2.3.  My 2.1 ESP Arduino still compiles with 1.6.12 - but OTA upload fails at 100% - perhaps that is fixed with update to the 2,3 update.

**Comment by nailbuster** [comment]
Hi,  I haven't had a need to update my IDE or ESP/github yet.....life has been busy this summer as well... 

Now that winter is coming, I'll have some more time to test it out on the newer versions....and hopefully see how to make it work with esp32 as well...

David

**Comment by Defragster** [comment]
Hi - nice if you get back to yours working. Mine was working so well when I abandoned it for working on the new Teensy My IDE's got updated. Suddenly I'm seeing ERROR[9] just after 100% and I can't find a reference to that.  But now I've jumped to the ESP 2.3 version thinking maybe the OTA update from IDE changed - same error . . .  Maybe I've forgotten something.

**Comment by Defragster** [comment]
I found the Teensy with the attached ESP8266 I used last and it is working for OTA uploads!
I used IDE 1.6.12 and ESP_Arduino 2.3 and compile and uploaded my last working version of the myWebServer.

I saw the IDE now includes a way to password protect OTA to ESP8266 so it should be safer to use, when I set that up.

Now to get back to that and connect the new Teensy 3.6.

**Comment by Defragster** [comment]
Going to close this - I opened a new 'Issue' indicating it working on the now current Arduino platforms: IDE 1.6.12 and ESP Rev 2.3
